### PR TITLE
Changes for issue #98 (Cuda/Metal/OpenCL properties)

### PR DESCRIPTION
**Pull request by barretpj**
I said I didn't know what I was doing with PRs, and maybe this proves it - despite my best efforts it's still showing 5 old commits in the list, although they have no effect on the diff.

### CODE REVIEW

**Comment by barretpj** [comment]
I don't seem to have privs to link this PR to the issue, I see no cog icon in the Development sidebar :-(

**Comment by garyo** [comment]
> I don't seem to have privs to link this PR to the issue, I see no cog icon in the Development sidebar :-(

You can always just mention the issue number like this: should fix #98. That will create enough of a link.

**Comment by garyo** [comment]
So the last 4 commits, [f41fdfe](https://github.com/ofxa/openfx/pull/101/commits/f41fdfe42f6017597b91359857366eb3d42df20e) through [db5a44d](https://github.com/ofxa/openfx/pull/101/commits/db5a44d3476ea9353db153c876230bd43525eabc) are the ones you want for this? I'll try applying those directly to main and see what happens.

**Review by garyo — COMMENTED** [review]
Looks good to me. I will submit a cleaned up version of this PR without the intermediate changes and reverts.

**Comment by garyo** [comment]
I cherry-picked the relevant commits onto main. Closing this as merged. Thanks, Phil!

**Pull request closed without merging**
