### PR TITLE
Examples: many fixes (mainly portability)

### PR DESCRIPTION
**Pull request by devernay**

### CODE REVIEW

**Comment by garyo** [comment]
Could you add the standard OFX copyright/disclaimer block at the top of the new files, esp. osxDeploy.h and Makefile.master?

**Comment by garyo** [comment]
Tested on Linux (Ubuntu/Mint), compiles OK.

**Comment by devernay** [comment]
I'll fix the copyright.

BTW, I also have a .travis.yml that does continuous integration on Travis (Ubuntu 12.04 and OSX 10.9). Are you interested? That way, any push triggers a build, and all pull requests trigger a build.

**Comment by garyo** [comment]
Yes, I'm very much in favor of hooking this up to Travis or any other CI server.  That would be great! (It would be ideal if it could build the doc too, but at least the samples would be very helpful.)

**Comment by garyo** [comment]
I'll merge this as soon as the copyright is in.  Then I think we're Go for releasing 1.4!

**Comment by devernay** [comment]
OK I pushed the copyright.

I just noticed the doc for progressStart in progress suite V2 was not updated in ofxProgress.h, can you fix it?

I'll do another pull request within the day to add ProgressSuiteV2 to hostsupport and support.

fred
--
Frédéric Devernay, Research Scientist, INRIA
frederic.devernay@inria.fr

**Comment by devernay** [comment]
I just fixed a few bugs in Examples & Support plugins related to the removal of normalized params

**Pull request merged**
