### PR TITLE
Create ofxDrawSuite.h

### PR DESCRIPTION
**Pull request by revisionfx**
Adding Paul Miller's Overlay Draw Suite proposal for review

### CODE REVIEW

**Comment by revisionfx** [comment]
Issues 74 and 75 ?

**Review by revisionfx — COMMENTED** [review]
Should Polygon and Ellipse be plural like Lines and Rectangles?
(or the opposite - something consistent)

**Comment by fxtech** [comment]
> Should Polygon and Ellipse be plural like Lines and Rectangles?
> (or the opposite - something consistent)

Probably not for Polygon - otherwise how would you know how many verts each one has?
I tried to make it analogous to glBegin/glEnd.

**Comment by revisionfx** [comment]
Paul, ok makes sense for Polygon
Maybe Rectangles should be singular? :)

**Comment by paul-miller-borisfx** [comment]
> Paul, ok makes sense for Polygon
> Maybe Rectangles should be singular? :)

Rectangles was meant as an analogue for GL_QUADS. And there isn't a GL_QUAD.

**Comment by revisionfx** [comment]
I see, then maybe it should be called Quads :)
Already two developers got it wrong  - treated this as glRectf   (2 coords)
And if quads then specify if CW or CCW in comment?

**Comment by fxtech** [comment]
> I see, then maybe it should be called Quads :)
> Already two developers got it wrong - treated this as glRectf (2 coords)
> And if quads then specify if CW or CCW in comment?

How about we replace it with RECTANGLE, and just require 2 coordines? That'll remove any ambiguity.

**Comment by revisionfx** [comment]
OK for 2 points rect for me

**Comment by revisionfx** [comment]
Paul, I updated Rectangles for Rectangle - and added an #if 0 for now if someone wants to support existing version in the wild using the original version.

**Comment by garyo** [comment]
Merged onto branch for review; please continue discussion in `feature/overlayDraw` branch or in issue #75

**Pull request merged**
